version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  restore:
    steps:
      - checkout
      - run: dotnet restore
  build:
    steps:
      - run: dotnet build
  test:
    steps:
      - run: dotnet test

workflows:
  version: 2
  build_and_publish:
    jobs:
      - restore
      - build
      - test
